services:
  fasten-health:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FASTEN_ENV=sandbox
    container_name: fasten-health
    restart: no

    ports:
      - "127.0.0.1:9090:8080"

    volumes:
      - ./dev_db:/opt/fasten/db
      - ./dev_cache:/opt/fasten/cache
      # - ./config.dev.yaml:/opt/fasten/config/config.yaml