version: '3.8'
services:
  fasten:
    # NOTE: only developers need to build Fasten from source
    # For production, use the pre-built image from GitHub Packages
    # ghcr.io/fastenhealth/fasten-onprem:main
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FASTEN_ENV=prod
#        - FASTEN_ENV=sandbox
    container_name: fasten-health-server
    ports:
      - "9090:8080"
      - "1901:1901"
    volumes:
      - ./fasten.db:/opt/fasten/db/fasten.db
      - ./dist:/opt/fasten/web
      - ./backend:/opt/fasten/backend  # Mount our local backend code
    environment:
      - FASTEN_ENV=development
    restart: unless-stopped
