version: "3.9"
services:
  fasten:
    # NOTE: only developers need to build Fasten from source
    # For production, use the pre-built image from GitHub Packages
    # ghcr.io/fastenhealth/fasten-onprem:main
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FASTEN_ENV=prod
#        - FASTEN_ENV=sandbox
    network_mode: "host"
    # environment:
    #   - FASTEN_EXTERNAL_HOST=${FASTEN_EXTERNAL_HOST}
    volumes:
      - ./db:/opt/fasten/db
      # - ./config.yaml:/opt/fasten/config/config.yaml
#      - ./config.example.yaml:/opt/fasten/config/config.yaml
