version: "3.9"
services:
  fasten:
    # NOTE: only developers need to build Fasten from source
    # For production, use the pre-built image from GitHub Packages
    # ghcr.io/fastenhealth/fasten-onprem:main
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FASTEN_ENV=prod
#        - FASTEN_ENV=sandbox
    depends_on:
      - typesense
    ports:
      - "9090:8080"
    volumes:
      - ./db:/opt/fasten/db
      - ./cache:/opt/fasten/cache
      - ./config.yaml:/opt/fasten/config/config.yaml
  typesense:
    image: typesense/typesense:29.0
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
    environment:
      - TYPESENSE_API_KEY=xyz123
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_ENABLE_CORS=true
    restart: unless-stopped
volumes:
  typesense-data: